name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: actions/setup-node@v7
        with:
          node-version: 20
          cache: npm
      - uses: workos/setup-socket-firewall@195977cfa38ab4d70363af5403a106dbc54a61eb
        with:
          token: ${{ secrets.PUBLIC_SOCKET_FIREWALL_TOKEN }}
          allow-external-fork-fallback: true
      - run: npm ci
      - run: npm run lint
      - run: npm run build
